#!python
#
# /usr/sbin/webapp-config
#       Python script for managing the deployment of web-based
#       applications
#
#       Originally written for the Gentoo Linux distribution
#
# Copyright (c) 1999-2005 Gentoo Foundation
#		Released under v2 of the GNU GPL
#
# Author(s)     Stuart Herbert <stuart@gentoo.org>
#               Renat Lumpau   <rl03@gentoo.org>
#               Gunnar Wrobel  <php@gunnarwrobel.de>
#
# ========================================================================
''' webapp-config is a powerful tool that allows you to install,
upgrade, and remove web-based applications in a virtual-hosting
environment.  '''

# ========================================================================
# Dependencies
# ------------------------------------------------------------------------

from WebappConfig.config import Config

def main():
    '''
    Main program call.
    '''
    # Get the configuration

    config = Config()

    config.parseparams()

    # Handle the work

    config.run()
    
if __name__ == "__main__":
    main()
